services:
    nestjs:
        build: ./server
        container_name: nestjs-app
        restart: always
        ports:
            - "3000:3000"
        env_file:
            - ./.env
        depends_on:
            mysql:
                condition: service_healthy
        environment:
            - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@mysql:3306/${MYSQL_DATABASE}
        networks:
            - app-network

    mysql:
        image: mysql:8.0
        container_name: mysql-db
        restart: always
        env_file:
            - ./.env
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - mysql-data:/var/lib/mysql
        ports:
            - "3307:3306"
        networks:
            - app-network
        healthcheck:
            test:
                [
                    "CMD",
                    "mysqladmin",
                    "ping",
                    "-h",
                    "mysql",
                    "-u",
                    "root",
                    "-p${MYSQL_ROOT_PASSWORD}",
                ]
            interval: 5s
            timeout: 5s
            retries: 20

networks:
    app-network:
        driver: bridge

volumes:
    mysql-data:
